sudo: false
language: c

services:
  - docker

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . -q
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
after_script:
  - docker pull p3lim/lua-doc-parser
  - docker run p3lim/lua-doc-parser
