sudo: false
language: c
python:
    - "3.6"

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_install: luarocks install --local luacheck

before_script: $HOME/.luarocks/bin/luacheck . -q
script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -o release.sh
  - bash release.sh -d

after_script:
  - curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/master/build_travis.sh -o build_travis.sh
  - curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/master/parse.py -o parse.py
  - bash build_travis.sh
