sudo: false
language: c
python:
    - "3.6"

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_install: luarocks install --local luacheck

before_script: $HOME/.luarocks/bin/luacheck . -q
script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
  - bash release.sh -d

after_script:
  - git clone "https://github.com/Gethe/lua-doc-parser.git" .
  - bash build_travis.sh
