sudo: false
language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc

install: luarocks install --local luacheck
script: /home/travis/.luarocks/bin/luacheck . -q
deploy: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
