name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Install and run Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q
        
    - name: Alpha Changelog
      if: contains(github.ref, 'tags') != true
      run: |
        echo $GITHUB_REF
        rm -f CHANGELOG.md

    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Parse Docs
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/https/parse.py -o parse.py
        curl -s https://raw.githubusercontent.com/Gethe/lua-doc-parser/https/build.sh | bash

    - name: Create Mainline Package
      uses: BigWigsMods/packager@master
      with:
        args: -o

    - name: Create Classic Package
      uses: BigWigsMods/packager@master
      with:
        args: -o -g 1.13.3 -m .pkgmeta-classic
